version: "3.8"

services:
  # Our NestJS Api
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      # Only build development stage from Dockerfile
      target: development
    # Mount our host dir to the docker container
    # Mount api directory (./api) to (:) docker container (/mblanchet/src/app)
    # Reflect File changes from host to container
    volumes:
      - ./api:/mblanchet/src/app
      - /mblanchet/src/app/node_modules/
    # RUN in debug mode: npm run start:debug --> Also start your vscode debugger
    # Run in dev mode: npm run start:dev
    command: npm run start:debug
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      JWT_SECRET: hard_to_guess_secret_123
      PORT: 3000
    ports:
      - "3000:3000"
      - "9229:9229"

  # Our Angular backoffice
  backoffice:
    build:
      dockerfile: Dockerfile
      context: ./backoffice
      target: development
    command: npm run start
    volumes:
      - ./backoffice:/mblanchet/backoffice/src/app
      - /mblanchet/backoffice/src/app/node_modules
    ports:
      - "8100:8100"
    links:
      - api

  frontoffice:
    build:
      dockerfile: Dockerfile
      context: ./frontoffice
      target: development
    command: npm run start
    volumes:
      - ./frontoffice:/mblanchet/frontoffice/src/app
      - /mblanchet/frontoffice/src/app/node_modules
    ports:
      - "4200:4200"
    links:
      - api

  # Our Postgres Database for NestJS to connect to
  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "35000:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  # The Postgres Admin tool if we want to run some custom queries and so on against our Database
  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin


volumes:
  local_pgdata:
  pgadmin-data:

